### ISSUE TITLE
Don't link libdl on FreeBSD

### ISSUE THREAD

**Issue by naptime** [DerelictOrg/DerelictUtil#12]
On (vanilla) FreeBSD, the dynamic loader is in libc, and passing -ldl to the linker (via 「"libs-posix": ["dl"]」, in package.json) breaks the build.

**Comment by aldacron** [comment]
OK. I'll push a fix for it soon. Thanks!

**Comment by aldacron** [comment]
I fixed this a while back, but forgot to close the issue.

https://github.com/DerelictOrg/DerelictUtil/commit/467b5b0409c59798ec85737d92fcb214ccc912de
