### ISSUE TITLE
Using platform-specific paths and env vars to load shared lib

### ISSUE THREAD

**Issue by drug007** [DerelictOrg/DerelictUtil#18]
Is it worth if SharedLibLoader would be able to use, for example, `LD_LIBRARY_PATH` or `/etc/ld.so.conf.d` to load the lib? It really helps to deploy the product but I'm not sure it should be implemented in SharedLibLoader instead of the user application.

**Comment by mdparker** [comment]
`dlopen` already searches `LD_LIBRARY_PATH` and `/etc/ld.so.cache`. See [the man page](http://man7.org/linux/man-pages/man3/dlopen.3.html).

**Comment by drug007** [comment]
Ok. I haven't checked it yet but I totally trust you.
