### ISSUE TITLE
master branch not compatible with DerelictSDL2

### ISSUE THREAD

**Issue by mpopetcmed** [DerelictOrg/DerelictUtil#9]
not really an issue with the code, but I couldn't find any better place to post this, maybe it will help others:

I've cloned both DerelictSDL2 and DerelictUtil on my machine and built the libraries using the 'dub  build' command. Then, trying to link these libraries to my simple app, I've run into issues (basically symbols not being found).

I think the cause is that while building DerelictSDL2, the 2.0 branch DerelictUtil is pulled (by 'dub build') and used instead. Then, the DerelictSDL2 library complains about missing symbols because I'm trying to link it to the 'master' version of the DerelictUtil (which is somewhat older than the active 2.0 branch).

The solution, of course, is to build the '2.0 branch' version of DerelictUtil library and use that in the linking step.

**Comment by aldacron** [comment]
The 2.0 branch of DerelictUtil is not the active branch -- the master branch is. Nearly all of the Derelict packages are dependent on the master branch, which is the 1.0.x version series. The 2.0 branch is currently the 1.9.x version series. The SDL-2.0.x branch depends on that and not master.

All of the Derelict packages are structured around the idea that most people will be using DUB to manage their projects. If you are going to manually pull stuff down and build it, then you absolutely have to pay attention to the dependency section of the dub.json files for each package you use and make sure you link the right versions.

The SDL2-
